---
title: "scatterplots for the final table"
author: "Zavadska Daryna"
date: "2023-05-24"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/home/dzavadska/Data/MAGs/MAGs_pre-final/Ext_tax_bug_corr_SMAGs_genus/all/")
```




```{r, echo=FALSE , message=FALSE}
##upload packages
library(stringr)
library(openxlsx)
library(data.table)
library(magrittr)
library(GGally)
library(propr)
library(data.table)
library(ggplot2)
library(reshape2)
library(tidyverse)
library(dplyr)
library(plyr)
library(microshades)
library(scales)
library(ggbreak) 
library(patchwork)
library(ggpubr)
library(gplots)
```

```{r, echo=FALSE, message=FALSE}


colors <-c(microshades_palette("micro_blue", lightest = FALSE), 
           microshades_palette("micro_purple", lightest = FALSE), microshades_palette("micro_cvd_purple", lightest = FALSE), 
           microshades_palette("micro_green", lightest = FALSE), 
           microshades_palette("micro_cvd_green", lightest = FALSE),
           microshades_palette("micro_orange", lightest = FALSE), 
           microshades_palette("micro_brown", lightest = FALSE), 
           microshades_palette("micro_cvd_turquoise", lightest = FALSE),
           microshades_palette("micro_cvd_gray", lightest = FALSE),
           microshades_palette("micro_cvd_orange", lightest = FALSE),
           microshades_palette("micro_gray", lightest = FALSE),
           microshades_palette("micro_cvd_blue", lightest = FALSE))


```








```{r}
#setwd("/home/dzavadska/Data/MAGs/REF2branch/data_outputs/for_fig1_scatterplots/")

vocabulary_fig1 <- fread("/home/dzavadska/Data/MAGs/REF2branch/data_outputs/candidate_pairs_edit1.csv")
listfiles <- list.files(pattern = "supergroup*data_V9_relabund_upd_ext_gen.tsv")
listfilesSMAG <- list.files(pattern = "supergroup*data_SMAGs_upd_ext_gen.tsv")


for (org in levels(as.factor(vocabulary_fig1$GENRE))) {
  print(org)
  if (org == "Geminigera") {next}
  #org <- "chloroparvula"
for (ONLYSMAG in levels(as.factor(vocabulary_fig1$SMAG))) {
  
  for (ONLYV9 in levels(as.factor(vocabulary_fig1$md5sum))) {
  
  local_vocabulary_fig1 <- vocabulary_fig1[which(vocabulary_fig1$GENRE == org),]
  local_vocabulary_fig1 <- local_vocabulary_fig1[which(local_vocabulary_fig1$SMAG == ONLYSMAG),]
  local_vocabulary_fig1 <- local_vocabulary_fig1[which(local_vocabulary_fig1$md5sum == ONLYV9),]
  
    if(nrow(local_vocabulary_fig1)==0){next}
  highlight_chloroparvula_IIIb <-levels(as.factor(local_vocabulary_fig1$SMAG))
  highlight_chloroparvula_IIIbV9 <- levels(as.factor(local_vocabulary_fig1$md5sum))
  highlight_chloroparvula_IIIbV9_X <- paste0("X", levels(as.factor(local_vocabulary_fig1$md5sum)))
  

OstrV9_file <- listfiles[grep(org, listfiles)]

    print(OstrV9_file)[1]
    if(length(OstrV9_file)==0){next}
    
OstrV9 <- fread(OstrV9_file[1],header = TRUE) %>% data.frame()

OstrSMAG_file <- listfilesSMAG[grep(org, listfilesSMAG)]    
OstrSMAG <- fread(OstrSMAG_file[1],header = TRUE) %>% data.frame()


    
OstrV9_trunc <- OstrV9[,c(1,which(colnames(OstrV9) %in% highlight_chloroparvula_IIIbV9), which(colnames(OstrV9) %in% highlight_chloroparvula_IIIbV9_X))]
OstrSMAG_trunc <- OstrSMAG[,c(1,which(colnames(OstrSMAG) %in% highlight_chloroparvula_IIIb))]     
    
#station_intersect <- which(OstrSMAG_trunc$V1 %in% OstrV9_trunc$V1 ==TRUE)
  station_intersect <- which( OstrV9$V1 %in% OstrSMAG_trunc$V1 ==TRUE)
    station_intersect_SMAG <- which( OstrSMAG_trunc$V1 %in% OstrV9$V1  ==TRUE)
    
    Genome <- OstrSMAG_trunc[station_intersect_SMAG,]
    #Genome <- OstrSMAG_trunc[station_intersect,]
    ControlV9 = OstrV9_trunc[station_intersect,]


    Ostr_relab <- merge(Genome,ControlV9,by="V1") 
    
    Ostr_relab <- Ostr_relab[order(Ostr_relab[,highlight_chloroparvula_IIIb], decreasing = TRUE),]
    Ostr_relab_m <-  melt(Ostr_relab,id.vars = "V1")
    Ostr_relab_m <- na.omit(Ostr_relab_m)
    Ostr_relab_m$fakest <- c(rep(c(1:length(unique(Ostr_relab_m$V1))),length(Ostr_relab_m$V1)/length(unique(Ostr_relab_m$V1))))
    

    Ostr_relab_m$class <- NA
    i<-1
      for (SMAGb in colnames(OstrSMAG_trunc)[-1]) {
         Ostr_relab_m$class[which(Ostr_relab_m$variable == SMAGb )] <- paste0("SMAG"," ", i)
         Ostr_relab_m$class_number[which(Ostr_relab_m$variable ==  SMAGb )] <-  i
         i <- i+1
      }
    
      i<-1
      for (V9 in colnames(OstrV9_trunc)[-1]) {
         Ostr_relab_m$class[which(Ostr_relab_m$variable == V9 )] <- paste0("V9"," ", i)
          Ostr_relab_m$class_number[which(Ostr_relab_m$variable == V9 )] <-  i
         i <- i+1
      }
      
    Ostr_relab_m$facet <- NA
      
    for (oneV9 in c(highlight_chloroparvula_IIIbV9)) {
        SMAGs_in_group <- local_vocabulary_fig1$SMAG[which(local_vocabulary_fig1$md5sum == oneV9)]
        V9_in_group <-  local_vocabulary_fig1$md5sum[which(local_vocabulary_fig1$SMAG  %in% SMAGs_in_group)]
        if (length(SMAGs_in_group)==0) {next}
        Ostr_relab_m$facet[which(Ostr_relab_m$variable %in% c(SMAGs_in_group, oneV9, paste0("X", oneV9), V9_in_group, paste0("X", V9_in_group)))] <- oneV9
      }
      
        
  for (numbers in  unique(Ostr_relab_m$class_number)) {
    
    df_to_plot <- Ostr_relab_m[which(Ostr_relab_m$class_number == numbers),]
    
    dotplot_to_save <-    ggplot(df_to_plot, aes(x=fakest, y=value,group = as.factor(variable))) + #geom_violin()+
  geom_point(size = 2, aes(shape = variable, colour = class))+theme_classic()+
      scale_color_manual(values = colors[c(57,40,6,7,33,34,35,24,25,23,36,37,38,39,40,59,60,20)])+ggtitle(org)
    
    print(dotplot_to_save)
  ggsave(dotplot_to_save, file=paste0( org, "_",ONLYSMAG,ONLYV9,  "candidate_pairs_scatterplot.svg"), width = 40.33333, height = 10, units = "cm", dpi=300,
       path = paste0("/home/dzavadska/Data/MAGs/REF2branch/plots/candidate_pairs_scatterplots/"))
    
  }    
######  
# Ostr_relab_m$class_feature <- NA
#  Ostr_relab_m$class_feature[grep("SMAG", Ostr_relab_m$class)] <- "SMAG"    
#  Ostr_relab_m$class_feature[grep("V9", Ostr_relab_m$class)] <- "V9"
 
#  plot_to_save <-  ggplot(Ostr_relab_m, aes(x=fakest, y=value,group = as.factor(variable))) + #geom_violin()+
#  geom_smooth(span = .1, size = 1, alpha = 0.45, aes(group = as.factor(variable), colour = class_feature, fill = class_feature))+
#  theme_classic()+facet_wrap(~facet)+theme(strip.text.x.top = element_blank())+
#  scale_color_manual(values = colors[c(57,40,6,7,33,34,35,24,25,23,36,37,38,39,40,59,60,20)])+ scale_fill_manual(values = colors[c(57,40,6,7,33,34,35,24,25,23,36,37,38,39,40,59,60,20)])+
  #geom_point(size = 0.5, aes(x=fakest, y=SMAGvaluebig, colour = class_number)) + 
#  labs(colour= "Feature", fill = "Feature")+xlab("Samples ranked by SMAG abundance ")+
     #scale_x_continuous(breaks = c(100,250,500))+
#  theme(legend.position="bottom")+ 
#  ylab("Relative abundance")+theme(text = element_text(size = 10),legend.text = element_text(size = 5), legend.title = element_text(size = 5))+guides(colour = "none", fill = "none", shape= "none", )
  
#print(plot_to_save)
  #ggsave(plot_to_save, file=paste0( org, "_", scenario,  "facet_wrap_scatterplot.svg"), width = 7.98, height = 6, units = "cm", dpi=300,
   #     path = paste0("/home/dzavadska/Data/MAGs/REF2branch/data_outputs/for_fig1_scatterplots/plots_fig1/"))
  
 ######## 
  
}

}
}


# plot_to_save <- ggplot(Ostr_relab_m, aes(x=fakest, y=value,group = as.factor(variable))) + #geom_violin()+
#  geom_smooth(span = .1, size = 1, alpha = 0.45, aes(group = as.factor(variable), colour = class_feature, fill = class_feature))+
#  theme_classic()+facet_wrap(~facet)+theme(strip.text.x.top = element_blank())+
#  scale_color_manual(values = colors[c(57,40,6,7,33,34,35,24,25,23,36,37,38,39,40,59,60,20)])+ scale_fill_manual(values = colors[c(57,40,6,7,33,34,35,24,25,23,36,37,38,39,40,59,60,20)])+
#  #geom_point(size = 0.5, aes(x=fakest, y=SMAGvaluebig, colour = class_number)) + 
#  labs(colour= "Feature", fill = "Feature")+xlab("Samples ranked by V9 OTU abundance ")+
#     scale_x_continuous(breaks = c(100,250,500))+
#  theme(legend.position="bottom")+ 
#  ylab("Relative abundance")+theme(text = element_text(size = 15),legend.text = element_text(size = 12), legend.title = element_text(size = 12))#+guides(colour = "none", fill = "none", shape= "none", )
 
#saving legend separately
#g_legend <- function(a.gplot){
 # tmp <- ggplot_gtable(ggplot_build(a.gplot))
#  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
#  legend <- tmp$grobs[[leg]]
 # return(legend)
#}

#mylegend <- g_legend(plot_to_save)
#library(grid)
#grid.draw(mylegend)


```












